
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
blackjackOptions <- R6::R6Class(
    "blackjackOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            cmds = NULL, ...) {

            super$initialize(
                package='jmvgames',
                name='blackjack',
                requiresData=TRUE,
                ...)
        
            private$..cmds <- jmvcore::OptionVariable$new(
                "cmds",
                cmds)
        
            self$.addOption(private$..cmds)
        }),
    active = list(
        cmds = function() private$..cmds$value),
    private = list(
        ..cmds = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
blackjackResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$..instructions,
        player = function() private$..player,
        dealer = function() private$..dealer,
        cards = function() private$..cards),
    private = list(
        ..instructions = NA,
        ..player = NA,
        ..dealer = NA,
        ..cards = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Blackjack")
            private$..instructions <- jmvcore::Preformatted$new(
                options=options,
                name="instructions",
                title="")
            private$..player <- jmvcore::Preformatted$new(
                options=options,
                name="player",
                title="Player")
            private$..dealer <- jmvcore::Preformatted$new(
                options=options,
                name="dealer",
                title="Dealer")
            private$..cards <- NULL
            self$add(private$..instructions)
            self$add(private$..player)
            self$add(private$..dealer)},
        .setCards=function(x) private$..cards <- x))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
blackjackBase <- R6::R6Class(
    "blackjackBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvgames',
                name = 'blackjack',
                version = c(1,0,0),
                options = options,
                results = blackjackResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Blackjack
#'
#' 
#' @param data .
#' @param cmds .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$player} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$dealer} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cards} \tab \tab \tab \tab \tab the order of the cards \cr
#' }
#'
#' @export
blackjack <- function(
    data,
    cmds) {

    options <- blackjackOptions$new(
        cmds = cmds)

    results <- blackjackResults$new(
        options = options)

    analysis <- blackjackClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
