
# This file is automatically generated, you probably don't want to edit this

blackjackOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "blackjackOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            cmds = NULL, ...) {

            super$initialize(
                package='jmvarcade',
                name='blackjack',
                requiresData=TRUE,
                ...)

            private$..cmds <- jmvcore::OptionVariable$new(
                "cmds",
                cmds)

            self$.addOption(private$..cmds)
        }),
    active = list(
        cmds = function() private$..cmds$value),
    private = list(
        ..cmds = NA)
)

blackjackResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        player = function() private$.items[["player"]],
        dealer = function() private$.items[["dealer"]],
        cards = function() private$..cards),
    private = list(
        ..cards = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Blackjack")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions",
                title=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="player",
                title="Player",
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="dealer",
                title="Dealer"))
            private$..cards <- NULL},
        .setCards=function(x) private$..cards <- x))

blackjackBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "blackjackBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvarcade',
                name = 'blackjack',
                version = c(1,1,0),
                options = options,
                results = blackjackResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Blackjack
#'
#' 
#' @param data .
#' @param cmds .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$player} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$dealer} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cards} \tab \tab \tab \tab \tab the order of the cards \cr
#' }
#'
#' @export
blackjack <- function(
    data,
    cmds) {

    if ( ! requireNamespace('jmvcore'))
        stop('blackjack requires jmvcore to be installed (restart may be required)')

    if ( ! missing(cmds)) cmds <- jmvcore::resolveQuo(jmvcore::enquo(cmds))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(cmds), cmds, NULL))


    options <- blackjackOptions$new(
        cmds = cmds)

    analysis <- blackjackClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
