
# This file is automatically generated, you probably don't want to edit this

hangmanOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "hangmanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            letters = NULL, ...) {

            super$initialize(
                package='jmvarcade',
                name='hangman',
                requiresData=TRUE,
                ...)

            private$..letters <- jmvcore::OptionVariable$new(
                "letters",
                letters)

            self$.addOption(private$..letters)
        }),
    active = list(
        letters = function() private$..letters$value),
    private = list(
        ..letters = NA)
)

hangmanResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Hangman")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))}))

hangmanBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "hangmanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvarcade',
                name = 'hangman',
                version = c(1,1,0),
                options = options,
                results = hangmanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Hangman
#'
#' 
#' @param data .
#' @param letters .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
hangman <- function(
    data,
    letters) {

    if ( ! requireNamespace('jmvcore'))
        stop('hangman requires jmvcore to be installed (restart may be required)')

    if ( ! missing(letters)) letters <- jmvcore::resolveQuo(jmvcore::enquo(letters))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(letters), letters, NULL))


    options <- hangmanOptions$new(
        letters = letters)

    analysis <- hangmanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
